# Generated by Django 3.1 on 2021-06-14 16:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('title', models.CharField(max_length=100, unique=True, verbose_name='Название категории')),
                ('slug', models.SlugField(primary_key=True, serialize=False, verbose_name='Слаг')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='children', to='product.category', verbose_name='Родительская категория')),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Название')),
                ('description', models.TextField(verbose_name='Описание')),
                ('image', models.ImageField(upload_to='products', verbose_name='Изображение')),
                ('status', models.CharField(choices=[('В наличии', 'В наличии'), ('Нет в наличии', 'Нет в наличии'), ('В ожидании', 'В ожидании')], max_length=20, verbose_name='Статус')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='products', to='product.category', verbose_name='Категория')),
            ],
            options={
                'ordering': ['-id'],
            },
        ),
    ]
