# Generated by Django 3.1 on 2021-06-15 09:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0002_content'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_name', models.CharField(max_length=100, verbose_name='Имя')),
                ('user_email', models.CharField(max_length=100, verbose_name='Почта')),
                ('user_phone', models.CharField(max_length=100, verbose_name='Телефон')),
                ('user_message', models.TextField(verbose_name='Сообщение')),
            ],
        ),
    ]
