# Generated by Django 3.1 on 2021-06-15 09:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0003_order'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='order',
            options={'ordering': ['-id']},
        ),
        migrations.AddField(
            model_name='order',
            name='user_status',
            field=models.CharField(choices=[('Новая', 'Новая'), ('В обработке', 'В обработке'), ('Готово', 'Готово')], default=1, max_length=100, verbose_name='Статус'),
            preserve_default=False,
        ),
    ]
