# Generated by Django 3.1 on 2021-06-15 09:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0004_auto_20210615_0916'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='user_status',
            field=models.CharField(choices=[('Новая', 'Новая'), ('В обработке', 'В обработке'), ('Готово', 'Готово')], default='Новая', max_length=100, verbose_name='Статус'),
        ),
    ]
